# Generated by Django 4.2.11 on 2024-04-25 00:27

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name', 'author']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-date', 'author']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=tasks.models.randomString, max_length=200, unique=True),
        ),
    ]
