# Generated by Django 4.2.11 on 2024-04-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_category_options_alter_tasks_options_and_more'),
    ]

    operations = [
    ]
