# Generated by Django 4.2.11 on 2024-04-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20240425_0127'),
    ]

    operations = [
    ]
