# Generated by Django 4.2.11 on 2024-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
