# Generated by Django 4.2.11 on 2024-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_options_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finished_task',
            field=models.BooleanField(default=False),
        ),
    ]
