# Generated by Django 4.2.11 on 2024-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tasks_finished_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='slug',
        ),
    ]
